<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l=[1,2,3,4,5,6]
x=np.array(l)
x

array([1, 2, 3, 4, 5, 6])

In [ ]:
#(start,end,step)

In [ ]:
x[::2]  #(all row, all0 colomn, step size 2)

array([1, 3, 5])

In [ ]:
x[1:4:2]

array([2, 4])

In [ ]:
import numpy as np
z=np.array([[11,22,33],[55,44,66],[12,34,56],[54,67,87]])
z

array([[11, 22, 33],
       [55, 44, 66],
       [12, 34, 56],
       [54, 67, 87]])

In [ ]:
z[1,1]

np.int64(44)

In [ ]:
z[:,::2]

array([[11, 33],
       [55, 66],
       [12, 56],
       [54, 87]])

In [ ]:
z[1:,1:]

array([[44, 66],
       [34, 56]])

In [ ]:
z[1:3,1]

array([44, 34])

In [ ]:
#for creating array in one dimention

In [ ]:
import numpy as np
np.arange(2,20,4)

array([ 2,  6, 10, 14, 18])

In [ ]:
np.random.randint(1,20,5)

array([ 4, 12, 13,  1, 17])

In [ ]:
#for same randon num
np.random.seed(12)  #12 is a batch no
np.random.randint(1,20,5)


array([12,  7, 18,  3,  4])

In [ ]:
np.random.seed(12)
np.random.randint(1,20,5)

array([12,  7, 18,  3,  4])

In [ ]:
np.random.rand(5)  # 0  se 1 ke beech ke combination deta hai

array([0.57339315, 0.63653014, 0.58076778, 0.31378165, 0.52633754])

In [ ]:
np.random.randn(5)  # combination of nagative and positive number

array([ 0.30209188,  1.07495638, -0.88582519,  0.11260228,  0.69414995])

In [ ]:
np.linspace(1,5,10) #equle distance batata hai

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
# d=final-initial/n-1

In [ ]:
# for 2 dimention array
x=np.linspace(1,5,10)
x.reshape(2,5)

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [ ]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)

print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#  arr[row_start:row_stop:step, column_start:column_stop:step]

In [ ]:

arr[:1:3,1:3,]


array([[2, 3]])

In [ ]:
arr[0:2:2,2:3:2]
arr[:
    ]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

x.reshape(5,2)

In [ ]:
# 1d me jitne toal element hote hai usko 2d me convert krne ke liye row and colomn ka mulpily total num ke equal hona chahiye reshape ka use karte hai


In [ ]:
#for 3d array
#(leyar,row,colomn)
# teeno ka multiply total num ke equal hona chahiye


In [ ]:
np.random.seed(12)
a=np.random.randint(1,100,24).reshape(2,3,4)
a

array([[[76, 28,  7,  3],
        [ 4, 68, 77, 49],
        [23, 50, 53,  6]],

       [[14, 90, 35, 76],
        [75,  1, 77, 14],
        [83, 90, 36, 63]]])

In [ ]:
a[:,0:3:2,1::2]

array([[[28,  3],
        [50,  6]],

       [[90, 76],
        [90, 63]]])

In [ ]:
b=np.random.randint(1,100,24).reshape(4,3,2)
b

array([[[55, 56],
        [85, 98],
        [21, 30]],

       [[70, 52],
        [44, 33],
        [44, 19]],

       [[71, 92],
        [35, 54],
        [59,  1]],

       [[38, 21],
        [81, 68],
        [88, 58]]])

In [ ]:
b[:, 1, :]

array([[85, 98],
       [44, 33],
       [35, 54],
       [81, 68]])

In [ ]:
# zero array
np.zeros((5,5),dtype=object)  # object ka matlab integer

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)

In [ ]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((4,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
a=np.random.randint(1,111,12).reshape(3,4)
a

array([[101,  36,  34,  31],
       [ 64,  97,  19,  87],
       [ 51,  81,  85,   7]])

In [ ]:
a=a>55
a

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a=[a>50]=10>


SyntaxError: cannot assign to comparison (4168506210.py, line 1)

In [ ]:
np.random.seed(22)
marks=np.random.randint(1,111,20).reshape(5,4)
name=np.array(['a','b','c','d'])
subjects=np.array(['maths','chem','phy','hindi','sans'])

In [ ]:
marks

array([[  5,  45,  65, 101],
       [103, 108,  85,   9],
       [ 96, 101,  94,  19],
       [ 15,  46,  89,  94],
       [ 40,  35,  42,   9]])

In [ ]:
# row ke liye axis 1
# column ke liye axis 0

np.sum(marks,axis=1)

array([216, 305, 310, 244, 126])

In [ ]:
np.sum(marks,axis=0)

array([259, 335, 375, 232])

In [ ]:
marks[0]

array([  5,  45,  65, 101])

In [ ]:
marks[0].max()

np.int64(101)

In [ ]:
# 0 1 0 1 0
# 1 0 1 0 1
#.....


In [ ]:
#convert one 2D to 1D
np.ravel()
np.platlen()

In [ ]:
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
np.arrange(1,13).reshape(4,3)
np.arrange(1,13).reshape(4,3)
x1

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
import numpy as np:
np.arrange(1,2,1)

In [ ]:
import numpy as np

arr = np.arange(1, 10,3).reshape(3,2)

print(arr)


ValueError: cannot reshape array of size 3 into shape (3,2)

In [ ]:
import numpy as np

arr = np.arange(1, 10,3).reshape(3, 2)

print(arr)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [ ]:
import random.randint
import numpy as np

arr = np.arange(1, 10,3).reshape(3, 2)

print(arr)

In [ ]:
#broad casting